//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPCMDPROJECT.SRWSProducto {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Producto", Namespace="http://schemas.datacontract.org/2004/07/SOAPPROJECT.Dominio")]
    [System.SerializableAttribute()]
    public partial class Producto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal precioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string productoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionField, value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idProducto {
            get {
                return this.idProductoField;
            }
            set {
                if ((this.idProductoField.Equals(value) != true)) {
                    this.idProductoField = value;
                    this.RaisePropertyChanged("idProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal precio {
            get {
                return this.precioField;
            }
            set {
                if ((this.precioField.Equals(value) != true)) {
                    this.precioField = value;
                    this.RaisePropertyChanged("precio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string producto {
            get {
                return this.productoField;
            }
            set {
                if ((object.ReferenceEquals(this.productoField, value) != true)) {
                    this.productoField = value;
                    this.RaisePropertyChanged("producto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RepetidoExcepcion", Namespace="http://schemas.datacontract.org/2004/07/SOAPPROJECT.Excepciones")]
    [System.SerializableAttribute()]
    public partial class RepetidoExcepcion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SRWSProducto.IProductos")]
    public interface IProductos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductos/CrearProducto", ReplyAction="http://tempuri.org/IProductos/CrearProductoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(APPCMDPROJECT.SRWSProducto.RepetidoExcepcion), Action="http://tempuri.org/IProductos/CrearProductoRepetidoExcepcionFault", Name="RepetidoExcepcion", Namespace="http://schemas.datacontract.org/2004/07/SOAPPROJECT.Excepciones")]
        APPCMDPROJECT.SRWSProducto.Producto CrearProducto(APPCMDPROJECT.SRWSProducto.Producto productoACrear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductos/CrearProducto", ReplyAction="http://tempuri.org/IProductos/CrearProductoResponse")]
        System.Threading.Tasks.Task<APPCMDPROJECT.SRWSProducto.Producto> CrearProductoAsync(APPCMDPROJECT.SRWSProducto.Producto productoACrear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductos/ObtenerProducto", ReplyAction="http://tempuri.org/IProductos/ObtenerProductoResponse")]
        APPCMDPROJECT.SRWSProducto.Producto ObtenerProducto(string producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductos/ObtenerProducto", ReplyAction="http://tempuri.org/IProductos/ObtenerProductoResponse")]
        System.Threading.Tasks.Task<APPCMDPROJECT.SRWSProducto.Producto> ObtenerProductoAsync(string producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductos/ModificarProducto", ReplyAction="http://tempuri.org/IProductos/ModificarProductoResponse")]
        APPCMDPROJECT.SRWSProducto.Producto ModificarProducto(APPCMDPROJECT.SRWSProducto.Producto productoAModificar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductos/ModificarProducto", ReplyAction="http://tempuri.org/IProductos/ModificarProductoResponse")]
        System.Threading.Tasks.Task<APPCMDPROJECT.SRWSProducto.Producto> ModificarProductoAsync(APPCMDPROJECT.SRWSProducto.Producto productoAModificar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductos/EliminarProducto", ReplyAction="http://tempuri.org/IProductos/EliminarProductoResponse")]
        void EliminarProducto(int idProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductos/EliminarProducto", ReplyAction="http://tempuri.org/IProductos/EliminarProductoResponse")]
        System.Threading.Tasks.Task EliminarProductoAsync(int idProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductos/ListarProductos", ReplyAction="http://tempuri.org/IProductos/ListarProductosResponse")]
        APPCMDPROJECT.SRWSProducto.Producto[] ListarProductos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductos/ListarProductos", ReplyAction="http://tempuri.org/IProductos/ListarProductosResponse")]
        System.Threading.Tasks.Task<APPCMDPROJECT.SRWSProducto.Producto[]> ListarProductosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductosChannel : APPCMDPROJECT.SRWSProducto.IProductos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductosClient : System.ServiceModel.ClientBase<APPCMDPROJECT.SRWSProducto.IProductos>, APPCMDPROJECT.SRWSProducto.IProductos {
        
        public ProductosClient() {
        }
        
        public ProductosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public APPCMDPROJECT.SRWSProducto.Producto CrearProducto(APPCMDPROJECT.SRWSProducto.Producto productoACrear) {
            return base.Channel.CrearProducto(productoACrear);
        }
        
        public System.Threading.Tasks.Task<APPCMDPROJECT.SRWSProducto.Producto> CrearProductoAsync(APPCMDPROJECT.SRWSProducto.Producto productoACrear) {
            return base.Channel.CrearProductoAsync(productoACrear);
        }
        
        public APPCMDPROJECT.SRWSProducto.Producto ObtenerProducto(string producto) {
            return base.Channel.ObtenerProducto(producto);
        }
        
        public System.Threading.Tasks.Task<APPCMDPROJECT.SRWSProducto.Producto> ObtenerProductoAsync(string producto) {
            return base.Channel.ObtenerProductoAsync(producto);
        }
        
        public APPCMDPROJECT.SRWSProducto.Producto ModificarProducto(APPCMDPROJECT.SRWSProducto.Producto productoAModificar) {
            return base.Channel.ModificarProducto(productoAModificar);
        }
        
        public System.Threading.Tasks.Task<APPCMDPROJECT.SRWSProducto.Producto> ModificarProductoAsync(APPCMDPROJECT.SRWSProducto.Producto productoAModificar) {
            return base.Channel.ModificarProductoAsync(productoAModificar);
        }
        
        public void EliminarProducto(int idProducto) {
            base.Channel.EliminarProducto(idProducto);
        }
        
        public System.Threading.Tasks.Task EliminarProductoAsync(int idProducto) {
            return base.Channel.EliminarProductoAsync(idProducto);
        }
        
        public APPCMDPROJECT.SRWSProducto.Producto[] ListarProductos() {
            return base.Channel.ListarProductos();
        }
        
        public System.Threading.Tasks.Task<APPCMDPROJECT.SRWSProducto.Producto[]> ListarProductosAsync() {
            return base.Channel.ListarProductosAsync();
        }
    }
}
