//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOAPTest.ClientesWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://schemas.datacontract.org/2004/07/SOAPPROJECT.Dominio")]
    [System.SerializableAttribute()]
    public partial class Cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string direccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string distritoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string telefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apellidos {
            get {
                return this.apellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.apellidosField, value) != true)) {
                    this.apellidosField = value;
                    this.RaisePropertyChanged("apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                if ((object.ReferenceEquals(this.direccionField, value) != true)) {
                    this.direccionField = value;
                    this.RaisePropertyChanged("direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string distrito {
            get {
                return this.distritoField;
            }
            set {
                if ((object.ReferenceEquals(this.distritoField, value) != true)) {
                    this.distritoField = value;
                    this.RaisePropertyChanged("distrito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idCliente {
            get {
                return this.idClienteField;
            }
            set {
                if ((this.idClienteField.Equals(value) != true)) {
                    this.idClienteField = value;
                    this.RaisePropertyChanged("idCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                if ((object.ReferenceEquals(this.nombresField, value) != true)) {
                    this.nombresField = value;
                    this.RaisePropertyChanged("nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.telefonoField, value) != true)) {
                    this.telefonoField = value;
                    this.RaisePropertyChanged("telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RepetidoExcepcion", Namespace="http://schemas.datacontract.org/2004/07/SOAPPROJECT.Excepciones")]
    [System.SerializableAttribute()]
    public partial class RepetidoExcepcion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ClientesWS.IClientes")]
    public interface IClientes {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientes/CrearCliente", ReplyAction="http://tempuri.org/IClientes/CrearClienteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SOAPTest.ClientesWS.RepetidoExcepcion), Action="http://tempuri.org/IClientes/CrearClienteRepetidoExcepcionFault", Name="RepetidoExcepcion", Namespace="http://schemas.datacontract.org/2004/07/SOAPPROJECT.Excepciones")]
        SOAPTest.ClientesWS.Cliente CrearCliente(SOAPTest.ClientesWS.Cliente clienteACrear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientes/CrearCliente", ReplyAction="http://tempuri.org/IClientes/CrearClienteResponse")]
        System.Threading.Tasks.Task<SOAPTest.ClientesWS.Cliente> CrearClienteAsync(SOAPTest.ClientesWS.Cliente clienteACrear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientes/ObtenerCliente", ReplyAction="http://tempuri.org/IClientes/ObtenerClienteResponse")]
        SOAPTest.ClientesWS.Cliente ObtenerCliente(string telefono);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientes/ObtenerCliente", ReplyAction="http://tempuri.org/IClientes/ObtenerClienteResponse")]
        System.Threading.Tasks.Task<SOAPTest.ClientesWS.Cliente> ObtenerClienteAsync(string telefono);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientes/ObtenerDatosCliente", ReplyAction="http://tempuri.org/IClientes/ObtenerDatosClienteResponse")]
        SOAPTest.ClientesWS.Cliente ObtenerDatosCliente(string tipo, string var);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientes/ObtenerDatosCliente", ReplyAction="http://tempuri.org/IClientes/ObtenerDatosClienteResponse")]
        System.Threading.Tasks.Task<SOAPTest.ClientesWS.Cliente> ObtenerDatosClienteAsync(string tipo, string var);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientes/ModificarCliente", ReplyAction="http://tempuri.org/IClientes/ModificarClienteResponse")]
        SOAPTest.ClientesWS.Cliente ModificarCliente(SOAPTest.ClientesWS.Cliente clienteAModificar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientes/ModificarCliente", ReplyAction="http://tempuri.org/IClientes/ModificarClienteResponse")]
        System.Threading.Tasks.Task<SOAPTest.ClientesWS.Cliente> ModificarClienteAsync(SOAPTest.ClientesWS.Cliente clienteAModificar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientes/EliminarCliente", ReplyAction="http://tempuri.org/IClientes/EliminarClienteResponse")]
        void EliminarCliente(string teelfono);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientes/EliminarCliente", ReplyAction="http://tempuri.org/IClientes/EliminarClienteResponse")]
        System.Threading.Tasks.Task EliminarClienteAsync(string teelfono);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientes/ListarClientes", ReplyAction="http://tempuri.org/IClientes/ListarClientesResponse")]
        SOAPTest.ClientesWS.Cliente[] ListarClientes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientes/ListarClientes", ReplyAction="http://tempuri.org/IClientes/ListarClientesResponse")]
        System.Threading.Tasks.Task<SOAPTest.ClientesWS.Cliente[]> ListarClientesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClientesChannel : SOAPTest.ClientesWS.IClientes, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClientesClient : System.ServiceModel.ClientBase<SOAPTest.ClientesWS.IClientes>, SOAPTest.ClientesWS.IClientes {
        
        public ClientesClient() {
        }
        
        public ClientesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClientesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SOAPTest.ClientesWS.Cliente CrearCliente(SOAPTest.ClientesWS.Cliente clienteACrear) {
            return base.Channel.CrearCliente(clienteACrear);
        }
        
        public System.Threading.Tasks.Task<SOAPTest.ClientesWS.Cliente> CrearClienteAsync(SOAPTest.ClientesWS.Cliente clienteACrear) {
            return base.Channel.CrearClienteAsync(clienteACrear);
        }
        
        public SOAPTest.ClientesWS.Cliente ObtenerCliente(string telefono) {
            return base.Channel.ObtenerCliente(telefono);
        }
        
        public System.Threading.Tasks.Task<SOAPTest.ClientesWS.Cliente> ObtenerClienteAsync(string telefono) {
            return base.Channel.ObtenerClienteAsync(telefono);
        }
        
        public SOAPTest.ClientesWS.Cliente ObtenerDatosCliente(string tipo, string var) {
            return base.Channel.ObtenerDatosCliente(tipo, var);
        }
        
        public System.Threading.Tasks.Task<SOAPTest.ClientesWS.Cliente> ObtenerDatosClienteAsync(string tipo, string var) {
            return base.Channel.ObtenerDatosClienteAsync(tipo, var);
        }
        
        public SOAPTest.ClientesWS.Cliente ModificarCliente(SOAPTest.ClientesWS.Cliente clienteAModificar) {
            return base.Channel.ModificarCliente(clienteAModificar);
        }
        
        public System.Threading.Tasks.Task<SOAPTest.ClientesWS.Cliente> ModificarClienteAsync(SOAPTest.ClientesWS.Cliente clienteAModificar) {
            return base.Channel.ModificarClienteAsync(clienteAModificar);
        }
        
        public void EliminarCliente(string teelfono) {
            base.Channel.EliminarCliente(teelfono);
        }
        
        public System.Threading.Tasks.Task EliminarClienteAsync(string teelfono) {
            return base.Channel.EliminarClienteAsync(teelfono);
        }
        
        public SOAPTest.ClientesWS.Cliente[] ListarClientes() {
            return base.Channel.ListarClientes();
        }
        
        public System.Threading.Tasks.Task<SOAPTest.ClientesWS.Cliente[]> ListarClientesAsync() {
            return base.Channel.ListarClientesAsync();
        }
    }
}
